# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe037b01a9f9cf3fb635ff4e841e5aab510c4850036d332a2c3fa430c3b97f8f3ec8969e5bfe6250ae4c60f7514faa5b34a499f36f6c3fb0a7a2a47341e97535

test:
  secret_key_base: 204b31d41c66bb72fce7a2f627b727ef7a010156c10f1e08fdf61d626cd2a4286a1fe1670f50e04192c7e35a8c1cf211671414e49b889de196a73fd8a251f64f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
